format_version: 10
pipelines:
  GoCD-Demo-Pipeline:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-0c1d873:
        git: https://github.com/go-training/helloworld.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - Build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Build:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -c
                - export PATH="/usr/local/go/bin:$PATH"
                - go build
                command: /bin/bash
                run_if: passed
    - Test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -c
                - export PATH="/usr/local/go/bin:$PATH"
                - go test
                command: /bin/bash
                run_if: passed
